name: Build

on: [push, pull_request]

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          tags: jamespfennell/transiter:latest
          outputs: type=docker

      - name: End-to-end tests (setup)
        run: docker-compose -f tests/endtoend/compose.yml up --build --detach sourceserver transiter db

      - name: End-to-end tests (run)
        run: docker-compose -f tests/endtoend/compose.yml up --build testrunner
    