name: Build

on: [push, pull_request]

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: jamespfennell/transiter-go:latest